ROLE_PERMISSIONS: dict[str, set[str]] = {
    "super_admin": {
        "menu.dashboard",
        "menu.exchange",
        "menu.positions",
        "menu.orders",
        "menu.assets",
        "menu.trades",
        "menu.research",
        "menu.news",
        "menu.users",
        "exchange.placeOrder",
        "positions.view",
        "positions.close",
        "positions.risk",
        "orders.detail",
        "orders.cancel",
        "assets.view",
        "assets.freeze",
        "trades.export",
        "research.view",
        "research.download",
        "research.bookmark",
        "news.view",
        "news.bookmark",
        "news.markRead",
        "users.view",
        "users.create",
        "users.edit",
        "users.disable",
        "roles.assign",
    },
    "risk_manager": {
        "menu.dashboard",
        "menu.exchange",
        "menu.positions",
        "menu.orders",
        "menu.trades",
        "menu.research",
        "menu.news",
        "menu.users",
        "exchange.placeOrder",
        "positions.view",
        "positions.close",
        "positions.risk",
        "orders.detail",
        "orders.cancel",
        "trades.export",
        "research.view",
        "research.download",
        "research.bookmark",
        "news.view",
        "news.bookmark",
        "news.markRead",
        "users.view",
    },
    "finance_operator": {
        "menu.dashboard",
        "menu.positions",
        "menu.assets",
        "menu.trades",
        "menu.research",
        "menu.news",
        "positions.view",
        "assets.view",
        "assets.freeze",
        "research.view",
        "news.view",
    },
    "auditor": {
        "menu.dashboard",
        "menu.positions",
        "menu.orders",
        "menu.assets",
        "menu.trades",
        "positions.view",
        "orders.detail",
        "assets.view",
        "research.view",
        "news.view",
    },
}


def has_permission(role: str, permission: str) -> bool:
    return permission in ROLE_PERMISSIONS.get(role, set())
